services:
  db:
    image: postgres:17-alpine3.22
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: gaster
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
